[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/contracts/=lib/chainlink/contracts/",
    "forge-std/=lib/forge-std/src/",
]

fs_permissions = [{ access = "read-write", path = "./deployments" }]

[fuzz]
runs = 256

[invariant]
runs = 256
depth = 50

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
